// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image_text: dynamic(() => import("./ImageText")),
  rich_text: dynamic(() => import("./RichText")),
};
